#!/usr/bin/env python3
"""Regenerate src/model.h for the edge-AI robot (lab 12).

This is intentionally dependency-free (plain Python 3, no numpy / no ML
framework, no internet): the "model" is a linear intent classifier whose
weights are keyword->intent affinities. We keep the spec here in a
readable form and emit the exact int8 table the firmware compiles in.

Run:  python3 tools/gen_model.py   (or `make model`), then `make`.

To teach the robot a new intent: add its keywords to INTENTS below (and a
matching plan in src/robot.c), regenerate, rebuild.
"""
import os

# Vocabulary (order defines the column index in the weight matrix).
VOCAB = [
    "walk", "forward", "backward", "back", "kneel",
    "hold", "still", "turn", "around", "left",
    "right", "patrol", "area", "stop", "halt",
    "home", "dock", "go", "return", "wait",
]

# Each intent scores on its characteristic words: {word: int8 weight}.
INTENTS = [
    ("PATROL",      {"patrol": 5, "area": 4, "around": 1}),
    ("RETURN_HOME", {"home": 5, "dock": 5, "return": 4, "go": 1}),
    ("KNEEL_HOLD",  {"kneel": 5, "hold": 4, "still": 3}),
    ("ADVANCE",     {"walk": 2, "forward": 5}),
    ("RETREAT",     {"walk": 2, "backward": 5, "back": 4}),
    ("TURN_AROUND", {"turn": 5, "around": 3, "left": 3, "right": 3}),
    ("STOP",        {"stop": 5, "halt": 5, "wait": 3}),
]

# Sample commands the firmware iterates through (only VOCAB words matter).
COMMANDS = [
    "walk forward",
    "walk backward",
    "kneel and hold still",
    "turn around",
    "patrol the area",
    "return home",
    "go to the dock",
    "stop and wait",
]

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "src", "model.h")


def build_matrix():
    idx = {w: i for i, w in enumerate(VOCAB)}
    rows = []
    for _, weights in INTENTS:
        row = [0] * len(VOCAB)
        for word, w in weights.items():
            row[idx[word]] = w
        rows.append(row)
    return rows


def c_str_array(name, items):
    body = ",\n    ".join(f'"{s}"' for s in items)
    return f"static const char *const {name}[] = {{\n    {body},\n}};\n"


def main():
    W = build_matrix()
    lines = []
    lines.append("/* AUTO-GENERATED by tools/gen_model.py -- see that file to edit. */")
    lines.append("#ifndef MODEL_H")
    lines.append("#define MODEL_H\n")
    lines.append("#include <stdint.h>\n")
    lines.append(f"#define VOCAB_SIZE  {len(VOCAB)}")
    lines.append(f"#define NUM_INTENTS {len(INTENTS)}\n")

    lines.append(c_str_array("vocab", VOCAB))
    lines.append(c_str_array("intent_names", [name for name, _ in INTENTS]))

    lines.append("static const int8_t model_W[NUM_INTENTS][VOCAB_SIZE] = {")
    for (name, _), row in zip(INTENTS, W):
        cells = ",".join(f"{v:2d}" for v in row)
        lines.append(f"    {{{cells}}},   /* {name} */")
    lines.append("};\n")

    lines.append(c_str_array("sample_commands", COMMANDS))
    lines.append("#define NUM_COMMANDS "
                 "((int)(sizeof(sample_commands) / sizeof(sample_commands[0])))\n")
    lines.append("#endif /* MODEL_H */")

    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {len(INTENTS)} intents x {len(VOCAB)} vocab words")


if __name__ == "__main__":
    main()
