#!/usr/bin/env python3
"""Train + quantize a tiny MLP on the 8x8 digits dataset and emit model.h.

This is a DEV-TIME tool, not part of the lab's runtime. It:
  1. trains a small float MLP (64 -> 32 -> 10, ReLU) on scikit-learn's
     8x8 handwritten-digit dataset,
  2. quantizes the weights to int8 with a per-layer scale,
  3. simulates the EXACT integer-only forward pass the C firmware runs
     (int32 accumulators + a right-shift requantization), so the C and
     Python predictions are bit-identical,
  4. picks the requant shift that maximizes integer-pipeline accuracy,
  5. writes src/model.h: int8 weights, int32 biases, the shift, and a
     handful of sample images (with true labels) that the integer model
     classifies correctly.

Re-generate with:  make model   (see the lab Makefile)
Requires numpy + scikit-learn (only to regenerate; the lab build does not).
"""
import os
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "model.h")

IN_DIM, HID_DIM, OUT_DIM = 64, 32, 10
N_SAMPLES = 10  # sample digits baked into the firmware


def quantize(w):
    """Symmetric int8 quantization. Returns (int8 array, scale)."""
    scale = np.max(np.abs(w)) / 127.0
    q = np.clip(np.round(w / scale), -127, 127).astype(np.int32)
    return q, scale


def int_forward(x, w1q, b1q, w2q, b2q, shift):
    """Integer-only forward pass — identical math to the C firmware."""
    # x: int32 vector of raw pixels (0..16)
    a = b1q + w1q @ x            # int32 accumulator, layer 1
    a = np.maximum(a, 0)         # ReLU
    h = np.clip(a >> shift, 0, 127)   # requantize to int8 range
    o = b2q + w2q @ h            # int32 accumulator, layer 2
    return int(np.argmax(o)), o


def main():
    X, y = load_digits(return_X_y=True)       # X in [0,16], shape (n,64)
    Xtr, Xte, ytr, yte = train_test_split(
        X, y, test_size=0.25, random_state=1, stratify=y)

    clf = MLPClassifier(hidden_layer_sizes=(HID_DIM,), activation="relu",
                        alpha=1e-3, max_iter=2000, random_state=1)
    clf.fit(Xtr, ytr)
    print(f"float MLP test accuracy: {clf.score(Xte, yte):.3f}")

    W1 = clf.coefs_[0].T        # (HID_DIM, IN_DIM)
    b1 = clf.intercepts_[0]     # (HID_DIM,)
    W2 = clf.coefs_[1].T        # (OUT_DIM, HID_DIM)
    b2 = clf.intercepts_[1]     # (OUT_DIM,)

    w1q, s1 = quantize(W1)
    w2q, s2 = quantize(W2)

    # Bias for layer 1 lives in the (w1q * x) domain: b1/s1.
    b1q = np.round(b1 / s1).astype(np.int32)

    # Sweep the requant shift; pick the one with best integer accuracy.
    # For each shift, hidden scale sh = s1 * 2^shift, so layer-2 bias is
    # b2 / (s2 * sh). argmax is invariant to the positive output scale.
    Xte_i = np.rint(Xte).astype(np.int32)
    best = None
    for shift in range(0, 12):
        sh = s1 * (2 ** shift)
        b2q = np.round(b2 / (s2 * sh)).astype(np.int32)
        correct = sum(int_forward(xi, w1q, b1q, w2q, b2q, shift)[0] == yi
                      for xi, yi in zip(Xte_i, yte))
        acc = correct / len(yte)
        if best is None or acc > best[0]:
            best = (acc, shift, b2q)
    acc, shift, b2q = best
    print(f"int8 pipeline test accuracy: {acc:.3f} (shift={shift})")

    # Pick sample digits the integer model gets right, one per class if we can.
    Xte_all = np.rint(Xte).astype(np.int32)
    chosen, seen = [], set()
    for xi, yi in zip(Xte_all, yte):
        pred, _ = int_forward(xi, w1q, b1q, w2q, b2q, shift)
        if pred == yi and yi not in seen:
            chosen.append((xi, int(yi)))
            seen.add(int(yi))
        if len(chosen) == N_SAMPLES:
            break

    emit(w1q, b1q, w2q, b2q, shift, chosen, acc)
    print(f"wrote {os.path.normpath(OUT)} with {len(chosen)} sample digits")


def carr(name, arr, ctype):
    """Format a flat C array initializer."""
    vals = ", ".join(str(int(v)) for v in arr.flatten())
    return f"static const {ctype} {name}[] = {{ {vals} }};\n"


def emit(w1q, b1q, w2q, b2q, shift, samples, acc):
    lines = []
    lines.append("/* AUTO-GENERATED by tools/gen_model.py — do not edit by hand.\n")
    lines.append(" * Tiny int8-quantized MLP (64 -> 32 -> 10) for 8x8 digits.\n")
    lines.append(f" * Held-out integer-pipeline accuracy: {acc*100:.1f}%\n")
    lines.append(" */\n")
    lines.append("#ifndef MODEL_H\n#define MODEL_H\n")
    lines.append("#include <stdint.h>\n\n")
    lines.append(f"#define IN_DIM   {IN_DIM}\n")
    lines.append(f"#define HID_DIM  {HID_DIM}\n")
    lines.append(f"#define OUT_DIM  {OUT_DIM}\n")
    lines.append(f"#define REQUANT_SHIFT {shift}\n")
    lines.append(f"#define N_SAMPLES {len(samples)}\n\n")
    # W1 stored row-major [HID_DIM][IN_DIM]
    lines.append(carr("model_w1", w1q, "int8_t"))
    lines.append(carr("model_b1", b1q, "int32_t"))
    lines.append(carr("model_w2", w2q, "int8_t"))
    lines.append(carr("model_b2", b2q, "int32_t"))
    lines.append("\n")
    imgs = np.array([s[0] for s in samples], dtype=np.int32)
    labs = np.array([s[1] for s in samples], dtype=np.int32)
    lines.append(carr("sample_images", imgs, "int8_t"))
    lines.append(carr("sample_labels", labs, "int8_t"))
    lines.append("\n#endif /* MODEL_H */\n")
    with open(OUT, "w") as f:
        f.writelines(lines)


if __name__ == "__main__":
    main()
