/* npu_transformer.c - the int8 transformer policy, compiled to run ON the
 * Google Coral NPU (rv32im), not on the host.
 *
 * This is the *functional* offload: the whole encoder block (embedding ->
 * self-attention -> feed-forward -> mean-pool -> classifier) executes on
 * the Coral core. The host stages a tokenized command into the DTCM
 * mailbox, releases the NPU from reset, and reads the predicted intent back
 * out of DTCM after the core halts (mpause).
 *
 * The weights are the SAME ones the host build uses (../../src/model.h,
 * generated by tools/gen_model.py) so host-side and NPU-side inference
 * agree bit for bit. All integer: int8 weights, int32 accumulate, an
 * integer-softmax LUT -- no FPU, no libc.
 *
 * Build with the CoralNPU / rv32im toolchain (see coralnpu/README.md):
 *   make -C coralnpu/kernel        # -> npu_transformer.elf + .bin
 */

#include <stdint.h>
#include "model.h"

/* ---- Host<->NPU mailbox in DTCM (NPU-local 0x10000 = host 0xE00010000) --
 * Kept inside the first 0x400 bytes of DTCM that link.ld reserves. */
#define DTCM_BASE        0x00010000u
#define IN_LEN           (*(volatile uint32_t *)(DTCM_BASE + 0x000))
#define IN_TOKENS        ((volatile uint32_t *)(DTCM_BASE + 0x004))  /* [SEQ_LEN] */
#define OUT_INTENT       (*(volatile uint32_t *)(DTCM_BASE + 0x100))
#define OUT_LOGITS       ((volatile int32_t *)(DTCM_BASE + 0x104))   /* [N_CLASSES] */
#define OUT_DONE         (*(volatile uint32_t *)(DTCM_BASE + 0x200))
#define DONE_MAGIC       0x00C0DE00u

/* If the host hasn't staged a command (IN_LEN == 0), fall back to this
 * built-in sequence so standalone runs on coralnpu_sim are meaningful.
 * {1,2} = "walk" "forward" -> ADVANCE. */
static const uint32_t default_tokens[] = {1, 2};
#define DEFAULT_LEN ((int)(sizeof(default_tokens) / sizeof(default_tokens[0])))

/* ---- transformer (identical math to the host reference) ------------- */
static void matvec_rc(const int8_t *W, int cols, int rows,
                      const int32_t *x, int32_t *y) {
    for (int r = 0; r < rows; r++) {
        int32_t acc = 0;
        const int8_t *w = W + (long)r * cols;
        for (int c = 0; c < cols; c++) acc += (int32_t)w[c] * x[c];
        y[r] = acc;
    }
}

static void attention(int32_t x[SEQ_LEN][D_MODEL], int len,
                      int32_t out[SEQ_LEN][D_MODEL]) {
    int32_t q[SEQ_LEN][D_MODEL], k[SEQ_LEN][D_MODEL], v[SEQ_LEN][D_MODEL];
    for (int i = 0; i < len; i++) {
        matvec_rc(&W_q[0][0], D_MODEL, D_MODEL, x[i], q[i]);
        matvec_rc(&W_k[0][0], D_MODEL, D_MODEL, x[i], k[i]);
        matvec_rc(&W_v[0][0], D_MODEL, D_MODEL, x[i], v[i]);
    }
    for (int i = 0; i < len; i++) {
        int32_t score[SEQ_LEN], best = -2147483647;
        for (int j = 0; j < len; j++) {
            int32_t s = 0;
            for (int d = 0; d < D_MODEL; d++) s += q[i][d] * k[j][d];
            score[j] = s;
            if (s > best) best = s;
        }
        int32_t w[SEQ_LEN], sum = 0;
        for (int j = 0; j < len; j++) {
            int32_t diff = best - score[j];
            if (diff < 0) diff = 0;
            if (diff >= SOFTMAX_LUT_SIZE) diff = SOFTMAX_LUT_SIZE - 1;
            w[j] = softmax_lut[diff];
            sum += w[j];
        }
        if (sum == 0) sum = 1;
        int32_t ctx[D_MODEL];
        for (int d = 0; d < D_MODEL; d++) {
            int32_t acc = 0;
            for (int j = 0; j < len; j++) acc += (w[j] * 128 / sum) * v[j][d];
            ctx[d] = acc >> 7;
        }
        matvec_rc(&W_o[0][0], D_MODEL, D_MODEL, ctx, out[i]);
    }
}

static void ffn(const int32_t x[D_MODEL], int32_t out[D_MODEL]) {
    int32_t h[D_FF];
    for (int f = 0; f < D_FF; f++) {
        int32_t acc = 0;
        for (int d = 0; d < D_MODEL; d++) acc += W_ff1[d][f] * x[d];
        h[f] = acc > 0 ? acc : 0;
    }
    for (int d = 0; d < D_MODEL; d++) {
        int32_t acc = 0;
        for (int f = 0; f < D_FF; f++) acc += W_ff2[f][d] * h[f];
        out[d] = acc >> 1;
    }
}

static int policy(const int *tokens, int len, int32_t logits[N_CLASSES]) {
    if (len == 0) len = 1;
    int32_t x[SEQ_LEN][D_MODEL];
    for (int i = 0; i < len; i++)
        for (int d = 0; d < D_MODEL; d++)
            x[i][d] = embedding[tokens[i]][d];

    int32_t att[SEQ_LEN][D_MODEL];
    attention(x, len, att);
    for (int i = 0; i < len; i++)
        for (int d = 0; d < D_MODEL; d++) att[i][d] += x[i][d];

    int32_t pooled[D_MODEL];
    for (int d = 0; d < D_MODEL; d++) pooled[d] = 0;
    for (int i = 0; i < len; i++) {
        int32_t fo[D_MODEL];
        ffn(att[i], fo);
        for (int d = 0; d < D_MODEL; d++) pooled[d] += att[i][d] + fo[d];
    }
    for (int d = 0; d < D_MODEL; d++) pooled[d] /= len;

    int best = 0;
    for (int c = 0; c < N_CLASSES; c++) {
        int32_t acc = 0;
        for (int d = 0; d < D_MODEL; d++) acc += W_cls[d][c] * pooled[d];
        logits[c] = acc;
        if (acc > logits[best]) best = c;
    }
    return best;
}

/* Returns the predicted intent, which crt0 leaves in a0 at mpause time so
 * a standalone `coralnpu_sim --i` run can read it with `reg info` (as well
 * as via the DTCM mailbox that the Renode host reads). */
int kernel_main(void) {
    int tokens[SEQ_LEN];
    int len = (int)IN_LEN;

    if (len <= 0 || len > SEQ_LEN) {
        len = DEFAULT_LEN;
        for (int i = 0; i < len; i++) tokens[i] = (int)default_tokens[i];
    } else {
        for (int i = 0; i < len; i++) tokens[i] = (int)IN_TOKENS[i];
    }

    int32_t logits[N_CLASSES];
    int intent = policy(tokens, len, logits);

    OUT_INTENT = (uint32_t)intent;
    for (int c = 0; c < N_CLASSES; c++) OUT_LOGITS[c] = logits[c];
    OUT_DONE = DONE_MAGIC;
    return intent;
}
